### ISSUE TITLE
API plan list times out in browser but works in curl

### ISSUE THREAD

**Issue by vbhavdal** [hmpf/easydmp#118] opened 2020-09-28 14:34 UTC
@hmpf Is this maybe some Nginx upstream timeout config that needs bump? (Why doesn't it fail in curl? Maybe that DRF decoration you get in browser.)

`curl https://easydmp.paas2.uninett.no/api/v1/plans/` works

whereas

just going to https://easydmp.paas2.uninett.no/api/v1/plans/ in browser leads to 502 Bad Gateway from nginx.

**Comment by hmpf** [comment] 2020-09-30 08:38
This is as you guessed caused by DRF decoration in the browser. A browser negotiates for html, and the html generation takes forever on the backend. This is due to a combination of:

- all plans being shown (not just published)
- having more than a thousand plans right now
- showing too much stuff in the list view for plans
- no paging

This will be fixed in v2 of the plan endpoint. Workaround: force use of json in the brwoser by suffixing "?format=json" to the url.

**Comment by hmpf** [comment] 2020-10-06 11:58
Closing this due to #124/#125. By using the query parameter "page_size" set to some integer, paging will be turned on with that max number of plans per page.

**Closed by hmpf** 2020-10-06 11:58 UTC
